from disnake.http import (
    DiscordClientWebSocketResponse,
    DiscordServerError,
    Forbidden,
    GatewayNotFound,
    HTTPClient,
    HTTPException,
    InvalidArgument,
    LoginFailure,
    MISSING,
    MaybeUnlock,
    NotFound,
    Route,
    json_or_text,
    to_multipart,
)
