from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from disnake.ext.commands.base_core import (
        AppCommandT,
        ApplicationCommand,
        ApplicationCommandType,
        ArgumentParsingError,
        BadArgument,
        BadBoolArgument,
        BadColorArgument,
        BadColourArgument,
        BadFlagArgument,
        BadInviteArgument,
        BadLiteralArgument,
        BadUnionArgument,
        BotMissingAnyRole,
        BotMissingPermissions,
        BotMissingRole,
        BucketType,
        ChannelNotFound,
        ChannelNotReadable,
        CheckAnyFailure,
        CheckFailure,
        CogT,
        CommandError,
        CommandInvokeError,
        CommandNotFound,
        CommandOnCooldown,
        CommandRegistrationError,
        ConversionError,
        CooldownMapping,
        DisabledCommand,
        EmojiNotFound,
        ErrorT,
        ExpectedClosingQuoteError,
        ExtensionAlreadyLoaded,
        ExtensionError,
        ExtensionFailed,
        ExtensionNotFound,
        ExtensionNotLoaded,
        FlagError,
        GuildNotFound,
        GuildStickerNotFound,
        HookT,
        InvalidEndOfQuotedStringError,
        InvokableApplicationCommand,
        MaxConcurrency,
        MaxConcurrencyReached,
        MemberNotFound,
        MessageNotFound,
        MissingAnyRole,
        MissingFlagArgument,
        MissingPermissions,
        MissingRequiredArgument,
        MissingRequiredFlag,
        MissingRole,
        NoEntryPointError,
        NoPrivateMessage,
        NotOwner,
        NSFWChannelRequired,
        ObjectNotFound,
        P,
        PartialEmojiConversionFailure,
        PrivateMessageOnly,
        RoleNotFound,
        T,
        ThreadNotFound,
        TooManyArguments,
        TooManyFlags,
        UnexpectedQuoteError,
        UnresolvedGuildApplicationCommandPermissions,
        UserInputError,
        UserNotFound,
        _get_overridden_method,
        async_all,
        guild_permissions,
        maybe_coroutine,
        warn_deprecated,
        wrap_callback,
    )

__all__ = (
    "InvokableApplicationCommand",
    "guild_permissions",
)

# isort: split
from disnake.ext.commands.base_core import __dict__ as __original_dict__

locals().update(__original_dict__)
