from disnake.types.voice import (
    GuildVoiceState,
    List,
    Literal,
    MemberWithUser,
    Optional,
    Snowflake,
    SupportedModes,
    TypedDict,
    VoiceIdentify,
    VoiceReady,
    VoiceRegion,
    VoiceServerUpdate,
    VoiceState,
    _PartialVoiceStateOptional,
    _VoiceState,
)
